import { check, finish, launch, WEB_URL } from './shared.mjs'

/** Journey through Phases 1–6: entry, universe, website, visit, back, search, filters, discovery, relationships, path, history. */
const mobile = process.argv.includes('--mobile')
const { browser, context, page, logs, wait, state: S, settle, enter } = await launch({ mobile })
const cam = () => page.evaluate(() => window.__webgalaxy.camera().position)
await enter()
console.log('source:', await page.evaluate(() => window.__webgalaxy.catalog.getState().source))

// Phase 3: enter universe, select, visit, back restores pose
await page.evaluate(() => window.__webgalaxy.store.getState().enterUniverse('ai')); await settle()
let s = await S(); check('enter universe', s.mode === 'universe' && s.u === 'ai')
const before = await cam()
await page.evaluate(() => window.__webgalaxy.store.getState().selectWebsite('chatgpt', 'ai')); await settle()
s = await S(); check('select website', s.mode === 'website' && s.w === 'chatgpt')
const [popup] = await Promise.all([context.waitForEvent('page', { timeout: 5000 }).catch(() => null), page.getByRole('button', { name: 'Visit Website', exact: true }).click()])
check('visit opens new tab', !!popup && /chatgpt\.com/.test(popup.url()), popup?.url()); if (popup) await popup.close()
await page.locator('section[aria-label$="details"]').getByRole('button', { name: 'Back', exact: true }).click(); await settle()
const after = await cam(); const delta = Math.hypot(...before.map((v, i) => v - after[i]))
check('back restores pose', delta < 0.5, `delta ${delta.toFixed(2)}`)
await page.evaluate(() => window.__webgalaxy.store.getState().selectWebsite('pubmed', 'science')); await settle()
check('sparse entry fallbacks', (await page.evaluate(() => [...document.querySelectorAll('section[aria-label="PubMed details"] button[disabled]')].map((b) => b.textContent).join('/'))).includes('No link'))
await page.keyboard.press('Escape'); await wait(300); await page.keyboard.press('Escape'); await settle()
s = await S(); check('esc chain → galaxy', s.mode === 'galaxy')

// Phase 4: search journey, filters, discovery, navigator
if (mobile) await page.getByRole('button', { name: /^Search/ }).tap(); else await page.keyboard.press('/')
await wait(300); await page.keyboard.type('git'); await wait(700)
const options = await page.evaluate(() => [...document.querySelectorAll('[role=option]')].map((o) => o.textContent.split('Universe')[0].split(' · ')[0].trim()))
check('search results', options[0].startsWith('GitHub') && options.some((o) => o.startsWith('GitLab')), options.slice(0, 3).join(','))
await page.keyboard.press('Enter'); await wait(800); s = await S(); check('journey started', s.t && s.w === 'github', JSON.stringify(s))
await settle(); check('journey arrived', (await S()).w === 'github' && (await page.evaluate(() => document.title)) === 'GitHub · The WebGalaxy')
await page.locator('section[aria-label$="details"]').getByRole('button', { name: 'Back', exact: true }).click(); await settle()
s = await S(); check('back from search focus → development view', s.mode === 'universe' && s.u === 'development')
await page.keyboard.press('f'); await wait(300)
await page.locator('select').nth(0).selectOption('cybersecurity'); await page.locator('select').nth(1).selectOption('planet'); await wait(500)
check('filters count', /^\d+ websites/.test(await page.evaluate(() => document.querySelector('section[aria-label="Filter the WebGalaxy"] [aria-live=polite]')?.textContent ?? '')), await page.evaluate(() => document.querySelector('section[aria-label="Filter the WebGalaxy"] [aria-live=polite]')?.textContent))
await page.getByRole('button', { name: 'Clear Filters' }).click(); await page.keyboard.press('Escape'); await wait(200)
await page.keyboard.press('e'); await wait(300); await page.getByRole('navigation', { name: 'Universes' }).getByRole('button', { name: /^Music/ }).click(); await settle()
check('navigator → music', (await S()).u === 'music')
await page.keyboard.press('d'); await wait(300); await page.getByRole('group', { name: 'Discovery modes' }).getByRole('button', { name: /^Random/ }).click(); await wait(3600)
s = await S(); check('random discovery found', s.d === 'travelling' || s.d === 'idle', `phase ${s.d} → ${s.w}`); await settle()

// Phase 5: relationships, highlight, path, cross-universe
await page.evaluate(() => window.__webgalaxy.store.getState().selectWebsite('github', 'development')); await settle()
s = await S(); check('relationships drawn', s.rel === 6 && s.rec.length === 3, `rel ${s.rel} rec ${s.rec}`)
check('panel related text', (await page.evaluate(() => document.querySelector('section[aria-label="Related websites"] .sr-only')?.textContent ?? '')).includes('GitLab (alternative)'))
await page.getByRole('button', { name: 'Explore Similar', exact: true }).click(); await wait(500); check('explore similar', (await S()).hl === 'similar')
await page.getByRole('button', { name: 'Works With', exact: true }).click(); await wait(300)
await page.locator('section[aria-label^="Works with"] button', { hasText: 'Vercel' }).click(); await settle()
s = await S(); check('follow to vercel', s.w === 'vercel' && s.path.slice(-2).join('>') === 'github>vercel')
await page.locator('section[aria-label$="details"] li button', { hasText: 'Cloudflare' }).first().click(); await settle()
s = await S(); check('cross-universe follow', s.u === 'cybersecurity' && s.w === 'cloudflare' && s.path.slice(-3).join('>') === 'github>vercel>cloudflare')
await page.locator('section[aria-label$="details"]').getByRole('button', { name: 'Back', exact: true }).click(); await settle()
s = await S(); check('back stays in cybersecurity', s.mode === 'universe' && s.u === 'cybersecurity')
await page.keyboard.press('e'); await wait(300)
check('history list', (await page.evaluate(() => document.querySelectorAll('section[aria-label="Recently explored"] li').length)) >= 3)
await page.keyboard.press('Escape'); await wait(200)
await page.evaluate(() => window.__webgalaxy.store.getState().leaveUniverse()); await settle()
s = await S(); check('galaxy clears path', s.mode === 'galaxy' && s.path.length === 0)
await finish(browser, logs)
